"""Initial schema

Revision ID: af475f2563b3
Revises: 
Create Date: 2025-12-03 22:32:51.807520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af475f2563b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('twilio_sid', sa.String(length=255), nullable=False),
    sa.Column('log_type', sa.Enum('CALL', 'MESSAGE', 'ERROR', 'WARNING', 'DEBUG', name='logtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('from_number', sa.String(length=50), nullable=True),
    sa.Column('to_number', sa.String(length=50), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_error_code'), 'logs', ['error_code'], unique=False)
    op.create_index(op.f('ix_logs_log_type'), 'logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_logs_processed'), 'logs', ['processed'], unique=False)
    op.create_index(op.f('ix_logs_status'), 'logs', ['status'], unique=False)
    op.create_index(op.f('ix_logs_timestamp'), 'logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_logs_twilio_sid'), 'logs', ['twilio_sid'], unique=True)
    op.create_table('monitoring_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('pattern_type', sa.Enum('ERROR_CODE', 'REGEX', 'STATUS', 'THRESHOLD', name='patterntype'), nullable=False),
    sa.Column('pattern_value', sa.Text(), nullable=False),
    sa.Column('threshold_count', sa.Integer(), nullable=True),
    sa.Column('threshold_window_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_rules_enabled'), 'monitoring_rules', ['enabled'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('EMAIL', 'WEBHOOK', 'LOG', name='actiontype'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['monitoring_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_enabled'), 'actions', ['enabled'], unique=False)
    op.create_index(op.f('ix_actions_rule_id'), 'actions', ['rule_id'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('action_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['log_id'], ['logs.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['monitoring_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_history_action_id'), 'alert_history', ['action_id'], unique=False)
    op.create_index(op.f('ix_alert_history_log_id'), 'alert_history', ['log_id'], unique=False)
    op.create_index(op.f('ix_alert_history_rule_id'), 'alert_history', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_history_success'), 'alert_history', ['success'], unique=False)
    op.create_index(op.f('ix_alert_history_triggered_at'), 'alert_history', ['triggered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_history_triggered_at'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_success'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_rule_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_log_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_action_id'), table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_actions_rule_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_enabled'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_monitoring_rules_enabled'), table_name='monitoring_rules')
    op.drop_table('monitoring_rules')
    op.drop_index(op.f('ix_logs_twilio_sid'), table_name='logs')
    op.drop_index(op.f('ix_logs_timestamp'), table_name='logs')
    op.drop_index(op.f('ix_logs_status'), table_name='logs')
    op.drop_index(op.f('ix_logs_processed'), table_name='logs')
    op.drop_index(op.f('ix_logs_log_type'), table_name='logs')
    op.drop_index(op.f('ix_logs_error_code'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
